"""``gbg schema``: the document Claude reads before writing SQL.

Generated from ``graphdef`` -- the same declarations that create the tables --
so it cannot describe a column that does not exist. Two layers:

* **static** (``docs/SCHEMA.md``, checked by ``--check``): tables, columns,
  relations, ids, macros, and the pitfalls section;
* **live** (``gbg schema`` against a built database): adds row counts and the
  actual values of enum-like columns, which is what stops a query from
  filtering on ``gcase = 'Nominative'`` when the data says ``nominative``.

The pitfalls come first on purpose. Each one is a wrong answer that looks
right -- most of all, reading MACULA's coreference ``subjref`` as the
grammatical subject.
"""

from __future__ import annotations

import sys
from pathlib import Path

from . import cli, db as dbmod, graphdef, ids

PITFALLS = [
    "**`has_subject` is coreference, not grammar -- and mostly for unexpressed subjects.** "
    "It links a verb to the word its subject refers to (MACULA `subjref`), usually in another "
    "verse. It is mainly present when the subject is not written out (90% of such verbs); "
    "only about 6% of verbs with an expressed subject carry one. Its presence is not a test "
    "of whether the subject is expressed -- keep every row a query returns. \"Every verb whose "
    "subject is Paul\" needs both: `has_subject`, plus the tree (`role = 's'`) and "
    "`refers_to` for pronoun subjects like ἐγώ. See the saved queries "
    "`subject_lemma_subjref` and `subject_lemma_tree`.",
    "**Lemmas match exactly, accents and case included.** `WHERE lemma = 'θεός'`. For "
    "accent-free lookup use `lemma_key = gbg_key('θεος')`; a key can match several lemmas "
    "(τίς/τις, εἰς/εἷς) -- report every match, never pick one.",
    "**Roles sit mostly on word groups.** `token.role` is set only when the word is itself a "
    "direct clause constituent; otherwise the role is on the `wg` above it. Check both.",
    "**Implicit participants have no target.** Rows with `implicit = true` in `refers_to`, "
    "`has_subject` and `frame_arg` have `dst IS NULL`; the `edge` view omits them.",
    "**Referent chains can cycle.** Guard every recursive query over `refers_to` with a "
    "visited list (see the saved query `referent_chain`).",
    "**Verses and sentences cross.** A sentence can span verses and a verse can be split "
    "across sentences; never assume one contains the other.",
    "**Cite tokens, verses and lemmas -- never word groups or sentences.** `wg` and "
    "`sentence` ids are build-local and change when upstream re-brackets.",
    "**Not in this build:** Louw-Nida semantic domains (not openly licensed), textual "
    "variants, and the Septuagint. Say so rather than answering from memory.",
    "**Meaning comes from two open, imperfect layers -- use both.** `token.english_terms` "
    "are stems of a translator's gloss (saved query `lemmas_by_gloss`: type plain English); "
    "`lemma_proximity` is Clear's Strong's-keyed synonym distance, LOWER = closer, each pair "
    "listed once in one direction (saved query `similar_lemmas`). Neither is a semantic "
    "domain: a passage can be about knowing without any knowing word. Say which layer found "
    "what.",
    "**Topical indexes are human judgements, in two different styles.** `naves_topic` "
    "(Nave's, 1896) is editorial and nested -- search its `path` -- but keyed to the KJV, so "
    "it can cite a verse for wording the SBLGNT lacks. `openbible_topic` comes from readers' "
    "votes: broad and noisy, so weigh `openbible_topic_verse.votes`. Topic ids are not "
    "citable; cite the verses. Saved queries `topics_matching`, `topic_verses`, "
    "`verse_topics`.",
    "**`gcase`, not `case`** (CASE is an SQL keyword).",
    "**Order:** surface order is `token.ord`; constituent order is `tree_ord` within a "
    "sentence. `surface` never includes punctuation -- that is in `after`.",
    "**A few values are upstream error notes.** Six `wg.role` values begin with `err` -- an "
    "annotator's note left where a role belongs. Filter on the documented role codes "
    "(`s`, `v`, `o`, `io`, `adv`, `p`, `vc`, `aux`, `o2`), never on `role IS NOT NULL`.",
    "**Frames are annotated as upstream annotated them.** An A0 list can include coordinated "
    "words and particles (2 John 1: ἐγώ, οὐκ, ἐγώ, ἐγνωκότες). Report what the rows say.",
]


def _table_md(t: graphdef.Table) -> list[str]:
    lines = [f"### `{t.name}` ({t.kind})", "", t.doc, "",
             "| column | type | null | links to | source | description |",
             "|---|---|---|---|---|---|"]
    for c in t.columns:
        link = f"`{c.ref}` ({c.label})" if c.ref else ""
        null = "" if c.nullable else "no"
        lines.append(f"| `{c.name}` | {c.type} | {null} | {link} | {c.component} | {c.doc} |")
    return lines + [""]


def static_doc() -> str:
    out = ["# Schema: the SBLGNT corpus graph", "",
           "Generated by `gbg schema --write` from `gbg/graphdef.py`. Do not edit by hand.",
           "", "## Read this first", ""]
    out += [f"{i}. {p}" for i, p in enumerate(PITFALLS, 1)]
    out += ["", "## Ids", "",
            "| kind | form | example | cite it? |", "|---|---|---|---|",
            f"| token | `{ids.EDITION}:<xml:id>` | `{ids.EDITION}:n57001001001` | yes |",
            f"| verse | `{ids.EDITION}:<USFM>.<ch>.<v>` | `{ids.EDITION}:PHM.1.20` | yes |",
            f"| book | `{ids.EDITION}:<USFM>` | `{ids.EDITION}:PHM` | yes |",
            "| lemma | `lemma:<NFC lemma>` | `lemma:θεός` | yes (shared across corpora) |",
            f"| sentence | `{ids.EDITION}:s:<leftmost token>` | `{ids.EDITION}:s:n57001001001` | no |",
            f"| word group | `{ids.EDITION}:wg:<leftmost token>.<depth>` | "
            f"`{ids.EDITION}:wg:n57001001001.1` | no |",
            "", "`gbg resolve \"Phlm 10\"` turns a reference into ids; `gbg ref` shows a passage.",
            "", "## Macros (stored in the database)", "",
            "- `gbg_key(s)` -- accent-, breathing-, case- and punctuation-free lookup key.",
            "- `gbg_nfc(s)` -- NFC normalisation (the form every stored string is in).",
            "", "## Tables", ""]
    for t in graphdef.TABLES:
        out += _table_md(t)
    out += ["## Relations", "",
            "Every relation appears in the `edge(src, dst, label, tier, src_table, dst_table)` "
            "view. Under `gbg sql --pgq` the same relations form the property graph "
            f"`{dbmod.PGQ_GRAPH}`, with these labels:", "",
            "| edge-view label | SQL/PGQ label | from | to | defined by |", "|---|---|---|---|---|"]
    for _name, _fill, src, _key, dst, label in dbmod.pgq_edge_tables():
        # An edge table's label is its own name; anything else is a foreign key.
        # (Prefix matching misfiles `lemma_proximity` as a column of `lemma`.)
        edge = graphdef.BY_NAME.get(label)
        if edge is not None and edge.kind == "edge":
            note = " (explicit targets only)" if any(c.name == "implicit"
                                                     for c in edge.columns) else ""
            out.append(f"| {edge.column('dst').label} | `{label}` | `{src}` "
                       f"| `{dst}` | table `{label}`{note} |")
        else:
            t = graphdef.BY_NAME[src]
            col = next(c for c in t.refs if f"{t.name}_{c.label.lower()}" == label)
            out.append(f"| {col.label} | `{label}` | `{src}` | `{dst}` | `{src}.{col.name}` |")
    out.append("| DOMINATES | `dominates` | `wg` | `token` | table `dominance` |")
    out += ["", "Example (`gbg sql --pgq`):", "", "```sql",
            f"FROM GRAPH_TABLE ({dbmod.PGQ_GRAPH}",
            "  MATCH (v:token)-[f:frame_arg]->(a:token)",
            "  WHERE v.lemma = 'ἀγαπάω' AND f.arg_role = 'A0'",
            "  COLUMNS (v.id AS verb, v.ref, a.id AS agent, a.surface))", "```", ""]
    return "\n".join(out)


def _one_line(v, width: int = 60) -> str:
    # Upstream sometimes stores a multi-line annotator note where a value belongs
    # (wg.role, six times); keep the doc readable without hiding that it happens.
    s = " ".join(str(v).split())
    return s if len(s) <= width else s[: width - 1] + "…"


def live_doc(db: Path) -> str:
    con = dbmod.connect(db)
    try:
        build_id, commits = dbmod._meta(con)
        out = ["", "## This build", "",
               f"build `{build_id}`, sources {', '.join(f'{k}@{v[:12]}' for k, v in commits.items())}",
               "", "| table | rows |", "|---|---|"]
        for t in graphdef.TABLES:
            n = con.execute(f'SELECT count(*) FROM "{t.name}"').fetchone()[0]
            out.append(f"| `{t.name}` | {n} |")
        out += ["", "### Values of enum-like columns", ""]
        for t in graphdef.TABLES:
            for c in t.columns:
                if not c.enum:
                    continue
                vals = con.execute(f'SELECT "{c.name}", count(*) FROM "{t.name}" GROUP BY 1 '
                                   f"ORDER BY 2 DESC, 1 LIMIT 25").fetchall()
                shown = ", ".join(("NULL" if v is None else f"`{_one_line(v)}`") + f" ({n})"
                                  for v, n in vals)
                out.append(f"- `{t.name}.{c.name}`: {shown}")
        return "\n".join(out) + "\n"
    finally:
        con.close()


def add_arguments(p) -> None:
    cli.add_db(p)
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--static", action="store_true", help="structure only (no database)")
    mode.add_argument("--write", action="store_true", help="write docs/SCHEMA.md")
    mode.add_argument("--check", action="store_true",
                      help="exit 2 if docs/SCHEMA.md differs from what graphdef generates")


def run(args) -> int:
    root = cli.root_of(args)
    target = root / "docs" / "SCHEMA.md"
    doc = static_doc()
    if args.write:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(doc, encoding="utf-8")
        print(f"wrote {target}")
        return cli.EXIT_OK
    if args.check:
        if target.is_file() and target.read_text(encoding="utf-8") == doc:
            print("schema --check: docs/SCHEMA.md matches graphdef")
            return cli.EXIT_OK
        print("schema --check: docs/SCHEMA.md is stale; regenerate with `gbg schema --write`",
              file=sys.stderr)
        return cli.EXIT_USAGE
    print(doc, end="")
    db = cli.db_of(args)
    if not args.static and db.is_file():
        print(live_doc(db), end="")
    return cli.EXIT_OK
